
#Client side config for CagedMobs. Do not change when shipping in ModPacks!
[client]
	#Disables entities models render to save on performance.
	disableEntitiesRender = false
	#Disables particles emitted by the cage upgrades
	disableUpgradesParticles = false
	#Disables entities growth progress render and keeps the size of the entity inside the cage always the same.
	disableGrowthRender = false
	#Disables environments (block models) render to save on performance.
	disableEnvsRender = false

